### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by darealshinji**
An attempt to fix the current babelfishy translation.

### CODE REVIEW

**Comment by Anime4000** [comment]
Thanks, currently I working on version 7

**Comment by darealshinji** [comment]
I couldn't find any language files in the master branch, that's why I chose the branch `ifme6`.

**Comment by Anime4000** [comment]
Had to wait :heart:

**Comment by moerxixi** [comment]
The Chinese language.(o^_^o)
`https://github.com/moerxixi/transpos/blob/master/cn.ini`

**Comment by Anime4000** [comment]
Guys, can you translate for version 7?
I am closing this commit due to incompatible format.
Please make new **Pull Request** 😺

**Pull request closed without merging**
