### PR TITLE
Added Brazilian Portuguese

### PR DESCRIPTION
**Pull request by ialexsilva**

### CODE REVIEW

**Comment by Anime4000** [comment]
is `ptb` is correct ISO code?
based on [this wiki](http://lingwiki.com/index.php?title=Brazilian_Portuguese) language, it uses `por`

**Comment by ialexsilva** [comment]
2 different languages Portuguese Portugal  (PT, POR, PT-PT) and Brazilian (PTB - PT-BR - BRA)


The most used is PT-BR

**Comment by ialexsilva** [comment]
Look this: 

https://msdn.microsoft.com/pt-br/library/ms533052(v=vs.85).aspx

**Comment by Anime4000** [comment]
mkvmerge give me:
`mkvmerge v9.2.0 ('Photograph') 64bit
Error: 'ptb' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerge --list-languages' for a list of all languages and their respective ISO639-2 codes.`

you can use `pt-br` in `language.json`

**Comment by ialexsilva** [comment]
Fixed

**Comment by Anime4000** [comment]
I am sorry 😢 
it appear mkvtoolnix, FFmpeg did not recognise `ptb` or `pt-br` ISO code
it seem they use 2 or 3 letter code langauge, [here for the full list](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by ialexsilva** [comment]
👌

**Comment by ialexsilva** [comment]
And now?

**Comment by Anime4000** [comment]
Good, I can merge 👍

**Pull request closed without merging**
