### PR TITLE
Update English translation

### PR DESCRIPTION
**Pull request by darealshinji**
Tried to fix a few things in the English translation.
There's one sentence I don't understand: `With this, you can reuse for others.`

Note: English is not my native language.

### CODE REVIEW

**Comment by Anime4000** [comment]
about `With this, you can reuse for others.`.
this message show when user save a new encoding preset.
I wanted to tell user, saving encoding preset allow user to re-use same preset for other video

**Comment by Anime4000** [comment]
@darealshinji sorry for interrupt, you know to compile mkvtoolnix and mp4box static, I modified your old sh code to match newer update, when I do `ldd`, still have link to some binary. like FFmpeg, when do `ldd` against static FFmpeg, ldd said `not dynamic executable`, how to achieve this?

here code I made:
https://github.com/Anime4000/IFME/blob/master/sources/build-mkvtoolnix.sh

**Comment by darealshinji** [comment]
Add `-static` to LDFLAGS. You could also try to use the binaries I've uploaded here for another project: https://sourceforge.net/projects/hybrid-tools/files/x86_64-linux-gnu/

**Comment by Anime4000** [comment]
Yesterday I add `-static`, run `rake` and give me this
Screenshot

and... this
https://sourceforge.net/projects/hybrid-tools/files/x86_64-linux-gnu/
wow, you make people life easier, nice project 👍

**Comment by darealshinji** [comment]
The symbol `pthread_mutex_unlock` is from the pthread library. You need to add it manually to the config file.
Here's how I built the last release of mkvtoolnix:
``` sh
./configure --without-gettext --disable-qt --enable-static
sed -i 's|^BOOST_SYSTEM_LIB = -lboost_system|BOOST_SYSTEM_LIB = -lboost_system -lpthread -pthread|g' build-config
sed -i 's|^MANPAGES_TRANSLATIONS = .*|MANPAGES_TRANSLATIONS =|g' build-config
rake -j6
```

**Comment by Anime4000** [comment]
@darealshinji nice, I can try out.
I agree about 32bit is obsolete, but people request it, so I had to make one, keep updating 64-bit

**Comment by Anime4000** [comment]
@darealshinji you know what cause of this problem? in 32-bit compile perfectly.
I reset my vm snapshot, and do again, still cannot
ubuntu 16 04 2 64-bit-2017-06-29-03-58-31

**Comment by darealshinji** [comment]
*_sin and *_cos sounds like sinus and cosinus. Try adding the math library to the libs: `-lm`

**Comment by Anime4000** [comment]
`VORBIS_LIBS = -lvorbis -lm` exist on `build-config`

**Comment by darealshinji** [comment]
Maybe you should just use the system libraries to build.
Running the following in a 32 bit chroot environment does it for me:
```
sudo apt install --no-install-recommends rake libbz2-dev liblzo2-dev \
  zlib1g-dev libmagic-dev libflac-dev libogg-dev libvorbis-dev libboost-dev \
  libboost-filesystem-dev libboost-regex-dev libboost-date-time-dev \
  libboost-system-dev pkg-config po4a docbook-xsl xsltproc

./configure --without-gettext --disable-qt --enable-static
sed -i 's|^BOOST_SYSTEM_LIB = -lboost_system|BOOST_SYSTEM_LIB = -lboost_system -lpthread -pthread|g' build-config
sed -i 's|^MANPAGES_TRANSLATIONS = .*|MANPAGES_TRANSLATIONS =|g' build-config
rake -j4
strip src/*
```

```
$ file src/mkvmerge 
src/mkvmerge: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=ceef8ad5eef1884c47e7c7eccc97c47298d00d72, stripped
```

**Pull request merged**
